// <auto-generated />
using Descartes.Contex;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Descartes.Migrations
{
    [DbContext(typeof(DiffContext))]
    [Migration("20201112165328_database")]
    partial class database
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Descartes.Entities.DifferenceObject", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("DiffResult")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DiffResult");

                    b.Property<string>("LeftValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LeftValue");

                    b.Property<string>("RightValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RightValue");

                    b.HasKey("Id");

                    b.ToTable("DifferenceObject");
                });
#pragma warning restore 612, 618
        }
    }
}
